### ISSUE TITLE
_OldArrayListTracks is not used, and can be deleted

### ISSUE THREAD

**Issue by tomlayg6** [BasicAirData/GPSLogger#106]
https://github.com/BasicAirData/GPSLogger/blob/1c03a905539b43ada7d50b5cf957365d8795d57f/app/src/main/java/eu/basicairdata/graziano/gpslogger/GPSApplication.java#L1330

**Comment by GrazianoCapelli** [comment]
Right, thanks. it's an unused piece of code.
