### ISSUE TITLE
Make the Notification more informative

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#115]
We are currently using the Notification Icon only to inform the User that the App is active.
By clicking on it, the User can open the main Activity of the Application.

We could be more informative, showing for example some Recording Data and/or the GPS Status.

**Comment by GrazianoCapelli** [comment]
I'm implementing a more informative Notification for GPS Logger as follows:

![notify_icon](https://user-images.githubusercontent.com/6907566/99148252-f9010980-2686-11eb-82e2-ecd043ed861a.png)

The new Notification follows these simple Rules:
- If the GPS status is NOT OK, the notification shows the status of the GPS. It could be "Looking for GPS", "Stabilizing Signal", ...
- if the GPS status is OK and the User is NOT recording, the Notification shows Ready state ("is active")
- if the GPS status is OK and the User is recording, the Notification shows _Duration_ and _Distance_

Furthermore, if the GPS is OK and the User is recording, the Notification Icon is different (it has a small dot inside).
This way the User can check that the Background Recording is OK without open the Notification Tray.

**Comment by JLJu** [comment]
It looks great to my! 👍

**Comment by GrazianoCapelli** [comment]
The feature has been implemented, and will be included into the next Update v2.3.0.
