### ISSUE TITLE
Feature Request : Consider adding the app in F-Droid

### ISSUE THREAD

**Issue by Chidhambararajan** [BasicAirData/GPSLogger#123]
Since the app is opensource , your app will get a lot of interest in F-Droid community
There are very few apps currently present in F-Droid which offers the same functionality

Just a suggestion

**Comment by Chidhambararajan** [comment]
Consider adding walking / trecking / jogging tracking feautres too

**Comment by GrazianoCapelli** [comment]
It is a duplicate of issue #8
