### ISSUE TITLE
Add Track color chooser

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#13]
A new settings in Exporting section in order to choose the track color for KML.
Could be cool to add extra options like "Color based on speed", "Color based on Altitude", and so on.

It is possible to change also the color of the GPX one?

**Comment by GrazianoCapelli** [comment]
We could add a preference screen showing:
- Type (Color 1; Color 2, Speed based; Altitude based, ...)
- Color 1 chooser;
- Color 2 chooser;

**Comment by GrazianoCapelli** [comment]
There are a lot of free Color Chooser libraries, many of them implement the preference too.
Sadly none of them is compatible with API 8 (actually one of them, but the graphics is really bad).

The alternatives are:
1) Continue the research; If anyone knows a good library that we could use, please link it here!
2) Drop API 8, 9, and 10. The library with lowest API I've found starts from API 11. Lots of them starts from API 14. I think their main problem is the integration with the old settings Android Library.
3) Bring that feature in standby.
4) Implement the color selection with a standard ListPreference, using a short list of predefined colors.
5) Start to make our own colorpreference;

I tend to a good combination between alternatives 1 and 3: a color chooser maybe isn't a good reason nor to drop compatibility and neither to reinvent the wheel.

**Comment by JLJu** [comment]
It's nice to have a good backward compatibility, in such a way many not so young Android devices can be reused as dedicated, expendables, GPS Loggers. I think we should also check with data on GPS Logger installation platforms. 

1 +3 looks good so far

**Comment by GrazianoCapelli** [comment]
I close this issue, if someone is interested to have/implement the feature, he can reopen it.
