### ISSUE TITLE
WW15MGH.DAC binary EGM Grid File is not available anymore from NGA Website

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#131]
The WW15MGH.DAC Binary EGM Grid File is not available from the NGA Website.
The GPS Logger App is unable to download the file (a 404 is returned).

On the NGA website the EGM Grid is available, in another format, from another link:
https://earth-info.nga.mil/wgs84/egm-download.php?file=EGM96/15_minute_interpolation_grid/EGM96_Interpolation_Grid.zip

It is a 2.9MB ZIP File that contains a 10MB WW15MGH.GRD File: the EGM96 grid saved in Text format instead of Binary.
The ZIP File contains also other utilities (two windows executables, a calculator in Fortran, a README file and so on.)

A new implementation of the Grid in GPS Logger should include the following steps:
1) Download of the 2.9MB Zipped Archive
2) Extraction (unzip) of the the 10MB WW15MGH.GRD Text File
3) Conversion of the file in Binary Format. As alternative we could use the TXT file, but the file reading will be 5 times slower that the binary one.

**Comment by GrazianoCapelli** [comment]
I found that a copy of WW15MGH.DAC file is hosted on the [OSGeo](https://www.osgeo.org/) Open Source Geospatial Foundation website.

The Open Source Geospatial Foundation (OSGeo) is a not-for-profit organization whose mission is to foster global adoption of open geospatial technology by being an inclusive software foundation devoted to an open philosophy and participatory community driven development.

It is a well known organisation that is developing some great applications like Marble, gvSIG, QGIS, GRASS GIS, and some Geospatial Libraries.

This is the direct link: http://download.osgeo.org/proj/vdatum/egm96_15/outdated/WW15MGH.DAC
The file is here since 2010-May-11.

Maybe could we use this link to download the EGM Grid with GPS Logger?

**Comment by JLJu** [comment]
The direct link by OSGeo is terrific news!

**Comment by GrazianoCapelli** [comment]
I propose to use the file hosted on the OSGeo.org website.
Please note that it is **NOT** a HTTPS secured connection, but an old HTTP one.
I think the visibility of the website is good all around the world. I implemented the download on the commit ba68b09.
I made some successfully tests: the WW15MGH.DAC is identical to the NGA's one (verified with diff), it downloads with a good speed and works great with GPS Logger.

As a Bonus, using this HTTP link we'll allow the download of the EGM file also with the old Android 4 devices (issue #67).
(Tested with my old Android 4.4 device).

_Time for suggestions & comments about!_
