### ISSUE TITLE
GPS not functioning well?

### ISSUE THREAD

**Issue by BertusvtW** [BasicAirData/GPSLogger#133]
Hi!

Since the installation of Android 11 the registration of GPS points is no longer as accurate as before. 
![WhatsApp Image 2021-04-13 at 18 03 51](https://user-images.githubusercontent.com/82463692/114584134-a1d98200-9c82-11eb-9bb2-79c3b7d104e3.jpeg)

As you can see in the picture there are two intervals in a straight line with no points.
I use a Samsung A40.

Thanks,

Bertus

**Comment by GrazianoCapelli** [comment]
If I understand well, you started the recording and, when you stopped it, the track is not complete in the middle (there are two straight lines, like a lack of GPS signal).

At your opinion, could be the recording stopped for some reason when the App was put in background?

You could first disable the battery optimizations:
1) Disable the Power Saving mode in favour of the Performance one: [https://www.sammobile.com/news/enable-ultra-power-saving-mode-in-one-ui-3-0/](https://www.sammobile.com/news/enable-ultra-power-saving-mode-in-one-ui-3-0/)
2) Follow the steps below (they should work for most Android phones with Oreo (Android 8.0) or above). Some smartphone manufacturers, however, completely replace Android's battery optimization for their own implementations. In those cases, you'll need to consult a manufacturer-specific tutorial.
- Start the Settings app and find Battery Optimization in the Apps section.
- At the top of the screen, tap "Not Optimized" and then tap "All apps." You should now see a list of all the apps on your phone. Each app is marked "Allowed" or "Not allowed." Allowed means that your phone is allowed to put the app to sleep when it's in the background.
- Find an app that you don't want to go to sleep, and tap it. In the pop-up, choose "Don't allow" and confirm your choice by tapping "OK."

**Comment by DazzyWalkman** [comment]
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/688
Maybe we are talking about The new "allowed all the time" location permission?
This app is facing the same issue linked above, I am not able to choose "allowed all the time",  GPS Logger 2.3.2, Android 11.

**Comment by GrazianoCapelli** [comment]
@DazzyWalkman - In GPS Logger the Location Service (that uses the GPS) is always enabled when the app is in foreground.
Once enabled, the GPSLogger's Foreground service (when is active, the notification icon is present on system toolbar) keeps the permission to use the GPS also if the app is put in background, and also if the GPS signal is temporarly lost.
This is the reason why GPS Logger asks to grant only the "_Allow only while using the app_" location permission.

The "_All the time_" permission is needed, for example, by services that request Locations in background without any user interaction.

_Technical documentation for Developers: https://developer.android.com/about/versions/11/privacy/location_

**Comment by GrazianoCapelli** [comment]
@BertusvtW - Did you resolved your issue by managing the energy saving settings?

**Comment by GrazianoCapelli** [comment]
@BertusvtW - I close this issue, because of inactivity, to keep our issue tracker clean. If you still need help, please provide the information I requested and I'd be happy to reopen it.
