### ISSUE TITLE
The local time recorded is incorrect

### ISSUE THREAD

**Issue by PierreDeQuebec** [BasicAirData/GPSLogger#147]
Hello,

The application does not record the local time correctly when I select the option "Show GPS time in time zone". There is a lag of +4 hours (in my case with recordings made in the Quebec City area). However, when the file is saved, the application automatically inserts an annotation with the date and the correct local time.

Per example:
T,2021-06-29 17:05:08,46.80863068,-71.11735919,4,65.131,-28.534,0.000,,15,21,20210629-130446,GPS Logger: 20210629-130446 - 1-nord-sud

Here, the time recorded by GPSLogger is 17: 05: 08,46.80863068 and the annotation reads 130446 (13h 04min 46s) (which is correct).

Best Regards

Pierre Lepage

**Comment by GrazianoCapelli** [comment]
Dear Pierre,
The local Time is used, for user convenience, only for:
- visualization in-app (when "_Show GPS time in time zone_" is set)
- naming the tracks

The app always exports all the Timestamps in [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) (also in TXT files), as required by KML and GPX standards. 

For this reason GPS Logger exports:
`T,2021-06-29 17:05:08` <-- UTC Time
`...1,20210629-130446,GPS Logger: 20210629-130446 - 1-nord-sud` <-- Name and Description of the track

in fact, the difference between the name and the time is approx -4 hours (Time zone in Quebec City, QC, Canada (GMT-4))

**Comment by PierreDeQuebec** [comment]
Thanks for your diligent response. I will therefore subtract the UTC offset to find the local time.

By the way, I am looking for a device to record altitude during bicycle tours. Do you have a suggestion for me? Currently, I am looking at the altimeters used for home-made rocket flights.

**Comment by GrazianoCapelli** [comment]
Unfortunately I cannot help you with a suggestion, because I am not informed on barometric altimeters.
I close this issue to keep our issue tracker clean. If you still need help, please feel free to reopen it.
