### ISSUE TITLE
Add an online help

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#15]
It would be nice to add a little online help, hosted on BasicAirData website and accessible even directly from the application.

We could include:
- Basic usage
- Description of the functions
- Description of the Settings
- Frequently Asked Questions
- Useful links

**Comment by JLJu** [comment]
Good idea. A compact help is welcome. 
You have my sword!
Contacting you via PM.

**Comment by GrazianoCapelli** [comment]
We are implementing the new _Online help_ item on the main menu this way:

![20210515 - Online_help](https://user-images.githubusercontent.com/6907566/118349290-248a8100-b550-11eb-935f-c88f19c8eda9.jpg)

This item opens the default browser and shows the getting started guide hosted on the BasicAirData website:
[https://www.basicairdata.eu/projects/android/android-gps-logger/getting-started-guide-for-gps-logger/](https://www.basicairdata.eu/projects/android/android-gps-logger/getting-started-guide-for-gps-logger/)
