### ISSUE TITLE
GPS Logger stops recording when screen is turned off

### ISSUE THREAD

**Issue by smartcooky** [BasicAirData/GPSLogger#153]
Samsung A8 (SM-A530F)
Android V9 (Kernel 4.4.111)
GPS Logger v3.0.0

I have logging set at 1 second intervals and Interface to "Keep Screen On"

I start a track, and lock screen, but if I turn off the screen manually, using the side button of the phone, the logger stops recording (I can see this because in TRACK the "Trackpoints" number has not incremented while the screen is turned off. 

a. When I manually turn screen back on, it takes about 15 - 20 seconds before it starts tracking again

b. I have noticed that if I swipe to watch GPX FIX, when I turn screen on again, it goes back to "Looking for GPS" again. Its as If GPS Logger stops looking at the GPS information while the screen is off. (This is probably why a. above is happening.)

I makes no difference if Interface is set to "Keep Screen On" or not

**Comment by GrazianoCapelli** [comment]
It seems that the app hasn't the permission to sun in background.
To avoid it, as first step, go to the Android settings and turn off all battery monitoring and optimizations for GPS Logger.
Check also that the application is NOT background restricted and verify that the background activity is allowed.
Unfortunately any device brand implemented in a different way the settings to keep safe the background apps (yes, it's a big mess), so a small research must be done.

For example you can start with the following settings:
- In Android Settings -> Apps -> GPS Logger -> Battery -> Optimise battery usage -> (select "All Apps" from the upper dropdown menu) -> (please uncheck GPS Logger)
- In Android Settings -> Device Maintenance -> Battery you should disable ther power saving mode (OFF) and disable the power monitoring for GPS Logger (in Unmonitored apps -> (three dots menu) -> Add apps -> GPS Logger

Moreover, other battery optimizers (like for example AccuBattery by Digibites) could restrict the background use, and also some anti-viruses are very aggressive with long running apps, and must be correctly set.

Hope it helps.

_PS: we suggest to update GPS Logger to the newest release, that fixed some bugs (not related to this topic)._

**Comment by smartcooky** [comment]
"For example you can start with the following settings:

    In Android Settings -> Apps -> GPS Logger -> Battery -> Optimise battery usage -> (select "All Apps" from the upper dropdown menu) -> (please uncheck GPS Logger)
    In Android Settings -> Device Maintenance -> Battery you should disable ther power saving mode (OFF) and disable the power monitoring for GPS Logger (in Unmonitored apps -> (three dots menu) -> Add apps -> GPS Logger"

This fixed it. Apps > Device Care > Battery > Power mode was set to "Medium power saving"

Thank you
