### ISSUE TITLE
Where did Max Speed reading go ?

### ISSUE THREAD

**Issue by kootzie** [BasicAirData/GPSLogger#157]
I am sure the first version of GPS logger had a max speed field by default
I remember doing multiple runs with my GT SnowRaycer sleds and being able to check the last run.
Along the way, I think there was an auto update, or maybe I installed the new version on a new phone, bit now poof, that feature was summarily excised and withdrawn.
I looked around in the settings and don't see any obvious way of turning it back on.

**Comment by GrazianoCapelli** [comment]
You can read the _Max Speed_ of the active track on the TRACK tab of the main activity.
The active Track data is visible only when you are recording a track, and is empty elsewhere.
The Max Speed appears when the app records the first FIX of the track that includes the Speed field (in fact not all fixes have the speed field, but usually almost all of them have it).

![max_speed](https://user-images.githubusercontent.com/6907566/149035025-354b4d6f-a8b9-49e4-a0ed-a44a3a29d883.png)

Furthermore, on TRACKLIST tab every recorded Track has its _max spd_ field.
But I have the feeling that I don't understood your request, please be more specific about your issue, maybe including some screenshots, and we'll try to help you.

**Comment by kootzie** [comment]
Great!
Thank you!
I didn't clue in to the multiple tabs...
I must have inadvertently poked on that TRACK tab at some point and the Max Speed magically appeared
and then more recently it magically disappeared.  I just tried it and sure enough there it is.
Thank you for the speedy response and for your program.  It is so simple and clean and elegant!

**Comment by GrazianoCapelli** [comment]
I close the issue.
Feel free to re-open it if you need further information.

Have a nice tracking!
