### ISSUE TITLE
some of the icons have CRC errors

### ISSUE THREAD

**Issue by IzzySoft** [BasicAirData/GPSLogger#160]
Some of the icons in `midmap-*` have CRC errors since the previous release – e.g. `mipmap-xxxhdpi-v4/gps_logger.png` and `mipmap-xxxhdpi-v4/gps_logger_big.png`. This causes errors when processing the APK with fdroidserver (e.g. to publish it in my repo). Could you please take a look and fix (also for the other resolutions)? It's as easy as opening and saving the file with e.g. GIMP. Thanks in advance!

**Comment by GrazianoCapelli** [comment]
We didn't change any image on the past releases, could it be due to the PNG Crunching that we disabled before the release v3.1.0? How can I check which images have CRC errors?

**Comment by IzzySoft** [comment]
I've noticed it by the errors fdroidserver threw. But then, `identify foo.png` threw them as well, so that could be used to identify affected files. `identify` is part of ImageMagick IIRC (checked: confirmed).

**Comment by GrazianoCapelli** [comment]
CRC errors fixed (commit aafaa69).

To remind me of that: I used optipng on Linux, directly from the res folder:
```optipng -fix `find . -type f -name "*.png"` ```

We should use this command every time we add or modify a png resource.
The lcons included using Vector Asset (the standard material icons) are already optimized.
@IzzySoft thanks again for the reporting!

**Comment by IzzySoft** [comment]
Great it worked out that fast! And eh, thanks for naming the `-fix` parameter to `optipng`. I also use `optipng` to optimize PNG images and it failed on those icons – now I know why :rofl:
