### ISSUE TITLE
Drive the app via keyboard hotkeys

### ISSUE THREAD

**Issue by joostbijl** [BasicAirData/GPSLogger#168]
Hi,

i'm using my phone to navigate on my motorcycle. I'm controlling the navigation app via a BT keyboard (via Arduino, see https://jaxeadv.com/gear-gadgets/navigation-setup/handlebar-buttons/). 

Is it possible to somehow make an annotation when i send a specific keystroke? This allows me to record interesting points while driving.

**Comment by GrazianoCapelli** [comment]
Hi,
I think it could be possible.
In case would you suggest some shortcut key scheme that is already used on another app (or single shortcut key normally used) that we could follow?

**Comment by GrazianoCapelli** [comment]
I report here the result of some test I made for fun, mainly for my convenience.
The keyboard hotkeys are relatively simple to add, we should only add this code into `GPSActivity.java`:

```java
@Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        if (event.getAction() == KeyEvent.ACTION_DOWN) {
            final int keyCode = event.getKeyCode();
            switch(keyCode){
                case KeyEvent.KEYCODE_R:     
                    // The "R" key toggles the recording state
                    gpsApp.setRecording(!gpsApp.isRecording());
                    break;
                case KeyEvent.KEYCODE_A:
                    // The "A" key triggers an annotation taking
                    gpsApp.setPlacemarkRequested(!gpsApp.isPlacemarkRequested());
                    break;
            }
            return true;
        }
        //return true;
        return super.dispatchKeyEvent(event);
    }
```
This way we would implement 2 hotkeys as example.
The list of hotkeys and functions to be associated to them should be defined.

At a date I have only a small problem: a key event selects the activity background, that becomes grey.
I should find a way to avoid this issue, maybe using a [StateListDrawable](https://developer.android.com/reference/android/graphics/drawable/StateListDrawable).

**Comment by GrazianoCapelli** [comment]
I added these shortcuts to the GPSActivity (the main Activity of GPSLogger):
- `R` = Start recording
- `P` = Pause recording
- `T` = Toggle recording
- `A` = Request an annotation (with input dialog)
- `Q` = Request a quick annotation (without input dialog)
- `S` = Stop recording (with finalizing dialog)
- `X` = Stop recording (without dialog)
- `1` = Show the GPS FIX Tab
- `2` = Show the TRACK Tab
- `3` = Show the TRACKLIST Tab

They can be used with a Bluetooth keyboard, but also to drive the app with task automation apps (for example [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en&gl=US), yet requested into issue #126).

Time for suggestions, ideas, and first tests.

**Comment by GrazianoCapelli** [comment]
The v3.1.4 has been published. The update includes the possibility to be driven with Hotkeys.
We published on https://www.basicairdata.eu a small webpage with the list of Hotkeys here:
https://www.basicairdata.eu/projects/android/android-gps-logger/application-note-gpslogger/gps-logger-hotkeys-list/

**Comment by Eule34** [comment]
How to send a key code with Macrodroid? Command "sent ident"?
Thanks for help.

![Screenshot_Sent_Intent_Marcordroid](https://user-images.githubusercontent.com/118726498/203025499-17b6e5e9-db07-41f1-a2ee-ed4280e64cf2.png)

**Comment by GrazianoCapelli** [comment]
Unfortunately I never used Macrodroid, thus I cannot give you a valuable help.

Since I'm curious, I taken a look to the app and I found nothing equivalent to [Tasker keyboard automation](https://tasker.joaoapps.com/userguide/en/help/ah_keyboard.html).
However I noticed that with Macrodroid you can emulate a click on screen using **UI interaction** feature, maybe you can try this way: emulate a click on the Record button once the app has been opened.

Speaking of GPS Logger, maybe in the future we could support the Intents to drive the app like we currently do with keys.
