### ISSUE TITLE
View tracks with any installed viewer, also if Google Earth is not installed

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#19]
A user's feedback on Google Play reports the following issue:

> _Only AFTER I install 'Google Earth' I am able to VIEW the route also with OTHER installed applications_

A little correction has to be made in order to discover if any viewer is available (like Locus Map) and, in case, show the "View" menuitem. The user will be able to choose his preferred viewer.

At the moment (v2.1.4) the "View in Google Earth" menu opens a chooser in case multiple viewers are installed. The problem is that that menu appears ONLY if Google Earth is installed.
That issue forces users to install Google Earth in order to view tracks using their preferred viewer (also NOT G.E.)

**Comment by GrazianoCapelli** [comment]
Code updated in commit 5ffec20.

Now the behavior is the following:

1) No viewers installed: the menuitem is hidden;
2) 1 viewer installed: the menu "View in App_Name" is shown (where "App_Name" is the name of the installed viewer);
3) Many viewers installed, default app set: the menu "View in App_Name" is shown (where "App_Name" is the name of the installed viewer);
4) Many viewers installed, no default app set: the menu "View in ..." is shown. The user will choose between them (like the "Share" menu) using a selector;

The code has been tested, and will be tested again, in order to be ready for the next app update.

_I'm thinking about the point 3: Maybe is better to force users to choose between apps also if a default one is set into the system. Is more annoying, but many users don't know how to revert a default app from Android settings._

**Comment by GrazianoCapelli** [comment]
Next app update will be published with the behaviour described above.
We check the users feedback and, in case, we'll evaluate to refine or modify it.

**Comment by JLJu** [comment]
User-driven. That's fine!
