### ISSUE TITLE
Can't find GPS signal

### ISSUE THREAD

**Issue by sromanowska** [BasicAirData/GPSLogger#197]
I've had an issue with the GPS Logger app not being able to find a GPS signal (it says 0 satellites are found). I've followed all of the location enabling instructions, so location services are enabled in phone settings and in the app. The battery optimization has been turned off, the newest software update has been downloaded, and GPS works on other location-based apps (e.g., Google Maps), so it should be good to record. I also closed and re-installed the app and re-started my phone. However, it will not let me record and just says that the GPS signal cannot be found. Has anyone else ran into this problem? Thank you!

**Comment by GrazianoCapelli** [comment]
Please post your phone model and your Android version, and we will check if we have good feedback from other users with the same device.

As first test you could check the real GPS signal and satellites (not the fused location, used for example by Google Maps) with the great free and opensource **GPS Test** app.
- GitHub repository with the source code: https://github.com/barbeau/gpstest
- Play Store page: https://play.google.com/store/apps/details?id=com.android.gpstest

You could also post here a screenshot of the satellites list.

**Comment by GrazianoCapelli** [comment]
@sromanowska - I close this issue, because of inactivity, to keep our issue tracker clean. If you still need help, please provide the information I requested and I'd be happy to reopen it.

**Comment by sourcevault** [comment]
I am having the same issue. 

Android 13, MIUI 13.2.1 (Custom ROM), would it possible to enable use of fusion GPS data if the user desires? every other map client uses it.

I say this since, my main usecase, goal of using this app is security, I want to be able to track my phone remotely.
