### ISSUE TITLE
Separation between data and data visualization in Track and Location objects

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#20]
There are many good reasons to divide the data string formatting from the numeric data:
- Removal of the duplication of code between Track and Location objects;
- We'll have Track and Location objects smaller, using less memory allocation, specially useful when load Location lists during exportation;
- Separation between data (access to DB) and data visualization (access to app strings);
- General performances improvements;
- We'll allow to easily implement the translations of the units of measurement;

The implementation of PhysicalData.java and PhysicalDataFormatter.java is started.
The goal is to add this improvement in the next app update.

**Comment by GrazianoCapelli** [comment]
Separation done and published in commit 5ffec20.
Now Units of Measurement are put in strings.xml, and fully translatable.

100% ready to add translation starting from the next update.

**Comment by JLJu** [comment]
Great. Strings translated to Spanish.
