### ISSUE TITLE
Clipboard: decimal format of GPS location

### ISSUE THREAD

**Issue by MusicalsAndJazz** [BasicAirData/GPSLogger#202]
The very useful clipboard feature copies the current coordinates onto the clipboard in the system locale settings. This seems fine at first sight, but unfortunately services like Google Maps seem to only use a fixed format to separate the integer part of a number from the decimals: the decimal point ("."). 
In my case, I use Android in German i.e. decimals are seperated by a comma (","), it means that I cannot share my location using the clipboard, as Google does not recognise this as correct coordinates.

Request:
Please set the clipboard copy format to "universal" so it is independent of the locale.

Thank you and keep up your excellent work!

**Comment by GrazianoCapelli** [comment]
Thanks for the very useful feedback, you reported an important wrong behaviour of the app.
I label this issue as bug, we'll fix it as soon as possible with an app update.

**Comment by GrazianoCapelli** [comment]
We just released the v3.2.1, that corrected this important bug.
We published it on Google Play, if you installed the app from there you should be able to see the update in 1 - 3 days.
We would e glad to have your feedback to be sure that now the feature works correctly.

I close the issue, feel free to reopen it in case of needs.

**Comment by MusicalsAndJazz** [comment]
> We just released the v3.2.1, that corrected this important bug. We published it on Google Play, if you installed the app from there you should be able to see the update in 1 - 3 days. We would e glad to have your feedback to be sure that now the feature works correctly.
> 
> I close the issue, feel free to reopen it in case of needs.

Hi Graziano, It now works perfectly. Thank you for your swift reaction and fixing!
