### ISSUE TITLE
 Difficulty testing and compiling with Android Studio - Guidelines?

### ISSUE THREAD

**Issue by AGuizolfe** [BasicAirData/GPSLogger#204]
We use GPS Logger to handle a demand for tracking and updating points of interest, however, we would like to test adjustments and help with improvements if possible. But we're having trouble making simple changes and we can't compile with Android Studio - Can anyone help, or give some guidance? Thanks in advance.... (Portuguese translated to English)

**Comment by GrazianoCapelli** [comment]
If you clone the repo and then open the project with the latest Android Studio, the app should compile without errors.
Please specify the steps you did to setup Android Studio and the project, and the error you are facing, and we'll try to help you.
Does your Android Studio work well with other GitHub projects?

What trouble are you having when you make simple changes?

_If you would like to follow our general guidelines to develop and contribute here, you can read the following document:
https://github.com/BasicAirData/GPSLogger/blob/master/CONTRIBUTING.md_

**Comment by GrazianoCapelli** [comment]
@AGuizolfe - I close the issue, because of inactivity, to keep our issue tracker clean.
If you still need help, feel free to comment or re-open the issue.
