### ISSUE TITLE
Precision position and altitudes from Trimble Mobile Manager 

### ISSUE THREAD

**Issue by teverth** [BasicAirData/GPSLogger#216]
I am planning to use the Trimble Mobile Manager App which uses a Trimble DA1 antenna and provides precision sub cm location data via a spoof gps to the android phone.

Will GPS Logger make use of the precision  position and altitude information or is that rounded down to normal GPS accuracy, and thereby throwing away the value of the precision data available from the Trimble receiver?

This connects to an earlier comment made on the precision of lat/lon.

The beauty of GPS Logger is it's simplicity. It would make a great addition to using the Trimble DA1 antenna in the field and record simple precision position information.

The Trimble Mobile Manager App calculates position data in cm level accuracy based on a subscription to the Trimble correction service.

One normally also has to subscribe to an app that allows to log the points. But GPS Logger would be a very easy to use app instead, if it would make full use of the precision offered by the Trimble Mobile Manager App.

**Comment by GrazianoCapelli** [comment]
GPS Logger stores and exports positions and altitudes with a resolution of **1mm**, regardless of the resolution of the GPS sensor.
Depending on the hardware, some devices can return more discretized data (it is not common to have a resolution of 1m for altitudes), and sometimes the same goes for the position.

GPS Logger can can use any external Bluetooth antenna compatible with your Android device.
To enable it you can read the following page:
https://www.basicairdata.eu/projects/android/android-gps-logger/application-note-gpslogger/using-a-bluetooth-gps-receiver-with-gps-logger/

**Comment by GrazianoCapelli** [comment]
@teverth - I close the issue, because of inactivity, to keep our issue tracker clean.
If you still need help, feel free to comment or re-open the issue.
