### ISSUE TITLE
Recommendations for geotagging DSLR photos

### ISSUE THREAD

**Issue by Offerel** [BasicAirData/GPSLogger#219]
Can you please give us some recommend settings  in your app, how to use it for geotagging photos,  shooting with a DSLR?

Basically I start a day by synchronizing the time of my phone to the camera,  to have identical timestamps on both devices. But I have no idea which settings to choose in your app, to save the phone battery and be so accurate as needed for photos later on. In my opinion,  accuracy is not that important for geotagging photos later on, but saving phone battery is important. My phone is mostly in my pocket during photo sessions. Traveling is sometimes by feed, sometimes via bus or railway. 

It would be nice to have some recommendations.

**Comment by mikeglee** [comment]
I have personally used GPSLogger for some years, and I could offer up two suggestions which would help you.

In Settings:
1. Turn "Keep Screen On" to Off
2. Change "GPS Update Interval" to 3 seconds

**Comment by GrazianoCapelli** [comment]
The app keeps the GPS always on when records a track, thus I might suggest to set:
- GPS update interval = 1 second, to have the maximum accuracy (in some devices the accuracy may decrease by setting an higher update interval) without affecting the battery consumption (if you use an interval of 3 seconds the battery consumption is pretty much similar). Anyway, the app doesn't use much battery during the recording, you can record for several hours without any problem
- Distance filter = 1 - 2 meters, to avoid to record points when you are still
- Keep Screen On = Disabled, as @mikeglee rightly suggested: the screen is the main battery drainer of a phone

**Comment by GrazianoCapelli** [comment]
@Offerel - I close this issue, because of inactivity, to keep our issue tracker clean.
If you still need help feel free to reopen it!
