### ISSUE TITLE
怎么记录“点”？

### ISSUE THREAD

**Issue by yang9w** [BasicAirData/GPSLogger#222]
只有轨迹，无法记录点位？

**Comment by GrazianoCapelli** [comment]
Hi yang9w,
i tried to translate your message, but I don't understand what you are asking.
please use the English language, (it should also be used for better readability by the community), and we'll try to answer your question.

**Comment by yang9w** [comment]
> Hi yang9w, i tried to translate your message, but I don't understand what you are asking. please use the English language, (it should also be used for better readability by the community), and we'll try to answer your question.

"How to record 'points'? That is, points of interest and so on. Currently, it only intelligently records trajectories, and I want to add coordinates for some points of interest."

**Comment by GrazianoCapelli** [comment]
It is possible to add annotations using the _Annotate_ button of the bottom bar, but you have already tried it for sure.
We consider the _Annotation_ feature the way to add points of interest, but I think that you are asking something different.
Please be more specific describing what you would like to have and, if you have some ideas, how/where it could be implemented.

**Comment by yang9w** [comment]
> It is possible to add annotations using the _Annotate_ button of the bottom bar, but you have already tried it for sure. We consider the _Annotation_ feature the way to add points of interest, but I think that you are asking something different. Please be more specific describing what you would like to have and, if you have some ideas, how/where it could be implemented.

I didn't notice, it must be what you said. I'll give it a try

**Comment by GrazianoCapelli** [comment]
Ok, we await your kind feedback
