### ISSUE TITLE
Preference for default export type

### ISSUE THREAD

**Issue by oucil** [BasicAirData/GPSLogger#223]
First, thanks for the quick reply on the play store, I was just heading back to correct my incorrect assessment that timestamps were not included when your note popped up. As you pointed out, they are, just in the GPX and TXT files, and not in KML as it's not part of the standard (which was surprising).

Right now, the default share file format is a KML file which does NOT include the timestamps. I would really like to be able to adjust the default share format via a settings preference to use the GPX format rather than having to dig into the filesystem to pull those out of the app data folder. 

Thanks for providing an excellent app! Is there a place I can buy you a beer or support your efforts?

**Comment by GrazianoCapelli** [comment]
Yes, the KML standard is born to show shapes on the 3D Earth and not to implement times and statistics, thus we cannot add timestamps to the tracks we export.
Fortunately there are other formats, for example the GPX, that are made on this purpose.

In GPS Logger there is the EXPORT preferences section where you can enable and disable KML, GPX, and TXT formats.
The formats you enable are used for exportation and also for sharing.

GPS Logger is set as default to export (and share) the tracks in both GPX and KML format.

About the beer, to date we have no way for receive donations.
Anyway many thanks for your kind thought!  :heart:

**Comment by GrazianoCapelli** [comment]
@oucil - I close the issue, because of inactivity, to keep our issue tracker clean.
If you still need help, feel free to comment or re-open the issue.
