### ISSUE TITLE
Add the system of measurement used in aviation and nautics

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#27]
Some users asked to implement the system of measurement used in aviation and nautics:
- Distance in Nautical Miles (nmi or NM), where 1 nmi = 1852 m;
- Speed in Knots (kn or kts), where 1 kn = 1.852 km/h; (one nautical mile (1.852 km) per hour)
- Altitude in feet (ft).

I specify that the new units are only for visualization purpose; GPX and KML files must be exported in the ISU.

**Comment by GrazianoCapelli** [comment]
The feature is relatively simple to implement.
I have some simple questions:
- Could we use _nmi_ to indicate nautical miles? Nautical miles could be indicated with _M_, _NM_, or _nmi_. We actually use _mi_ to indicate statutory miles. It's a good idea to stay sticked to _mi_ simbol to indicate nautical miles? Or it is better to differentiate them and use NM?
- kn or kts?
- How can we name this system of measurement? _Aeronautical_ would be fine?

**Comment by JLJu** [comment]
Based on common material
http://www.bipm.org/en/publications/si-brochure/   "Complete brochure (French and English, 8th edition)" Pag 127
+
Garmin Marine Screen shot 
http://www.uship.fr/gps-lecteur-de-cartes-garmin-gpsmap-7400-iaddz-37888-2.jpg
+
Garmin Pilot Screen shot
https://www.garmin.com/en-US/blog/wp-content/uploads/2013/11/6a00d83451bb7069e2019b00a9c820970c-400wi.jpg
I think following UOM are fine
- NM
- kn
-Aerial/Nautical units of measurement

**Comment by GrazianoCapelli** [comment]
Basing on your good observations, I think we could start the implementation of the conventions you suggested:
- Nautical Miles = NM
- Knots = kn
- Name of the new UOM = Aerial / Nautical

We can change anytime in case of new elements or new ideas.

**Comment by GrazianoCapelli** [comment]
We can easily provide, in the same and yet implemented way, the selection of speeds UM.
I suggest the following choices:
- Knots (kn);
- Statutory miles per hour (mph), specially useful for american area.

**Comment by GrazianoCapelli** [comment]
Feature implemented (commit 3935717).

Thanks to all GPSLogger translators, I have already imported from Crowdin all the new required strings.
Thus, the feature is completed in all languages, and ready for tests.

It will be included in the next update, the v.2.1.7.

**Comment by GrazianoCapelli** [comment]
Tests done. Feature ready for inclusion.

**Comment by JLJu** [comment]
Thumbs up!
