### ISSUE TITLE
Create files for Viewing & Sharing in private FilesDir instead of AppData

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/GPSLogger#34]
Actually the Exporter creates the temporary files in /GPSLogger/AppData public folder, but it should create them into the FilesDir private space and pass them to other apps using a URI generated by a FileProvider.
The proper way to share files in Android is well explained [here](https://developer.android.com/training/secure-file-sharing/setup-sharing.html).

Following this way we'll have 2 benefits:
1) It will be possible to View / Share files without Storage permission;
2) The /GPSLogger folder will contain only the exported files: no more /AppData subdirectory!

**Comment by GrazianoCapelli** [comment]
Opened the branch issue-34 in order to manage it.

The feature is already full implemented and committed into this branch.
I noted, with a bit of disappointment, that many visualizers adopt different politics depending on the position of shared file:
- If the file is in a public folder (like /GPSLogger/AppData), then the app opens it from the original location;
- If the file comes from a private folder and it is passed via FileProvider, the app saves a copy into a shared folder and then opens the shared file (to avoid the expiration of the temporary read permission);

If we generate the file into our private folder, the viewers adopt the second behaviour.
As result, each time the user views the track, the viewer saves a new copy of the file into a shared folder, causing many duplicates of the same file.

Thus, this method isn't applicable to "View" feature.

We could use the new method for "Share" feature, but maybe it's better to leave both as are.

**Comment by JLJu** [comment]
To use the same philosophy for both functions seems good to me

**Comment by GrazianoCapelli** [comment]
Branch closed
