### ISSUE TITLE
Icon / Logo design proposal

### ISSUE THREAD

**Issue by s-yous** [BasicAirData/GPSLogger#44]
Hello @GrazianoCapelli ,
I'm a graphic designer and i'm asking for your permission to design an icon and a logo for your application.

**Comment by GrazianoCapelli** [comment]
To date we already have a well identifiable, and (maybe) relatively well made app's icon, that we have not in plan to change. Anyway, small adjustments and improvements are welcome.
As alternative, if you want to help, we could propose a slightly different graphical work:

1) You can start from our PNG icon, or from the SVG one, (background and foreground images) and create the XML version of them
2) currently we don't have a good banner image, you could design and propose a new one

Before contributing please read our license; we can include your work only if you can release it under the same license or a compatible one.
As you can see, we are used to share the artworks also in native format.
