### ISSUE TITLE
Feature Requests: Add comments/Name field

### ISSUE THREAD

**Issue by zeus-web** [BasicAirData/GPSLogger#46]
Hi, 

What I really miss, is a possibility to 
- edit the name of a track
- add tags and/or comments to a track 

so I could find them more easy later on.

Thanks for the great and handy tool, anyway!!

BR
Nico

**Comment by GrazianoCapelli** [comment]
When we re-designed the new tracklist we added the "Track Number" field under the Track Name, with the idea to place here (in the future) an optional user description of the track.

![Track_Description](https://user-images.githubusercontent.com/6907566/71319805-789c4d80-24a3-11ea-96b2-beca8b0c6db6.jpg)

We have a future plan to implement the possibility to add Comments and Name field into a new "_Track Details_" Activity.
In this new screen will be possible to edit some other Track data (like Placemarks for example).
The issue #47 is dedicated to discuss and develop the Details activity.

I close the issue #46: if anyone wants to deepen this topic, please refer to the issue #47 instead.
Thanks @zeus-web for his useful proposals!
