### ISSUE TITLE
Feature Request: Edit details of a track

### ISSUE THREAD

**Issue by zeus-web** [BasicAirData/GPSLogger#47]
Would be great, if I could edit the details of a track, e.g. if a track is wrong categorized as "by car" Track.

Thanks in advance :-)

**Comment by GrazianoCapelli** [comment]
It is for sure a good feature to add.
We are thinking for a long time to add a new activity that shows the details of a track.
On this new screen the user could view all the details of each track (i.e. total and moving statistics, summary, placemarks list, maybe some graph - like speed and altitude - and so on), and it should also be possible to change some track properties (like name, type...).
The good news is that we can gradually implement new features on this activity screen, starting from a simple summary with a couple of editing capabilities.

_This new activity needs a UI design mockup before to start the implementation._

**Comment by GrazianoCapelli** [comment]
When we re-designed the new tracklist we added the "Track Number" field under the Track Name, with the idea to place here (in the future) an optional user description of the track.

![Track_Description](https://user-images.githubusercontent.com/6907566/71319805-789c4d80-24a3-11ea-96b2-beca8b0c6db6.jpg)

We could add the possibility to add/edit this description into the Details Activity.
This description could be used to name the exported files, in order to produce file names like this:

`20190618-053234 - Travel around the Area 51.gpx`

**Comment by GrazianoCapelli** [comment]
In these days I tried to sketch a first mockup of an hypothetical future Details Activity, with the purpose to collect all the UI elements and to have a first idea about the activity structure.
In this mockup the Activity is a simple scrollable area; only the upper part (toolbar and map) is fixed.
![Edit_Mock_03](https://user-images.githubusercontent.com/6907566/81944548-35cb4580-95fd-11ea-857a-5d01a8c77cbb.jpg)
The "Track" section could be present only if there are trackpoints collected;
The "Placemarks" section could be present only if the recording has placemarks;

Just clicking on the text/icon field, We could:
- Add / Edit the name (description)
- Change the track type
- Edit the description of the placemarks

Anyone can post suggestions, ideas, comments, completely different mockups...

**Comment by trentonbrochill** [comment]
Any update on this? I really want to have the ability to mark the track with a description. For my use case, using the phone or user name in the name/description would also work.

**Comment by GrazianoCapelli** [comment]
@trentonbrochill - We'll start soon to add a Dialog when the user finalize a Track (instead of an Activity screen), with the possibility to specify a Description (and maybe to correct the activity icon).
The same Dialog could be re-opened by adding an icon to the ActionMode Toolbar of the Tracklist.
We spoken about this feature some weeks ago on issue #88.

This is one of the most requested features, I think that this could be present into the next App Update (v2.3.0).

**Comment by GrazianoCapelli** [comment]
These days we are working on the new bottom bar (issue #88), where the **Stop** button shows a dialog that ask finalize the track.
This dialog allows the user to edit the track description and the activity type:

![photo_2021-04-19_20-43-02](https://user-images.githubusercontent.com/6907566/115288845-398f1280-a152-11eb-8041-4cb2d1effd7a.jpg)

The same dialog will be used on the Tracklist to edit the track details.
Currently we are in early implementation phase, it is a good time to post suggestion and ideas!

**Comment by GrazianoCapelli** [comment]
Added an **Edit** button on Actionbar, that opens the **Edit details** dialog (commit 01c0900).

![Screenshot_20210425-120847_GPS Logger](https://user-images.githubusercontent.com/6907566/115989605-72e6d880-a5bf-11eb-9744-9f8f4d783833.jpg)

The editing dialog is the same dialog as the one used for track finalization (except for the title).
The button is visible only when one single track has been selected (like the View button).

This could yet be a good initial implementation of the feature for now.
In the future we could expand the functionality including, for example, an editor for Placemarks.

**Comment by GrazianoCapelli** [comment]
Commit b5ebecf added the description field into KML, GPX, and TXT files.
The GPX format (with the new `<desc>` field) has been validated using [Xerces](https://xerces.apache.org/) v2.8.0.

**Comment by GrazianoCapelli** [comment]
The feature reached a good implementation level and it has been merged into the develop branch.
It will be refined before the publication of the next app update.

At this time the implementation of the files management is done as follows:
The tracks are saved as GPX/KML/TXT and managed with the `NAME - Description` file name.
For example `20190618-053234 - Travel around the Area 51.gpx`.

When a user exports a track, then he changes the description and export again, the app today leaves the old file into the GPSLogger folder. This means that the user will have 2 files of the same track into the folder, with 2 different descriptions.
For me it is not bad. Better to have a file more than a file less.
As alternative we could remove the old file before the creation of the new one (the app could do this without any problem, the code is already used for Temporary files), by find all the Tracks that start with the same name (on the previous example `20190618-053234`. This way the folder will be more polished, but not all users could agree when the app deletes files.

Furthermore, using the implemented method, the user could save different version of the same tracks (for example with and without EGM correction, or with different GPX standard), simply by changing the description of the track and exporting.

Which way could be the best one?

**Comment by GrazianoCapelli** [comment]
The feature has been implemented on v3.0.0.
I close this issue. If in the future we'll think a different (or more complete) implementation of the details editing, we'll open another issue or we'll reopen this one.
