### ISSUE TITLE
Manual download of EGM grid

### ISSUE THREAD

**Issue by DazzyWalkman** [BasicAirData/GPSLogger#61]
This issue does NOT require any action from the developer. I open this issue only to share my little "findings".

The app will download EGM grid from: 
http://earth-info.nga.mil/GandG/wgs84/gravitymod/egm96/binary/WW15MGH.DAC.
This is essentially a US military website, that means it's inaccessible from certain parts of the world, thus users of this app in these regions will not be able to download EGM grid from the above website.

I am one of them. I just query the WW15MGH.DAC via search engine, and find suitable mirror links to download the file, then place it into the phone internel storage /GPSLogger/AppData/ folder or whatever user-config FileDir. 

It seems to work well, though I cannot share links for I can't back the authenticity of such file from unknown sources.

Hope it helps.

**Comment by GrazianoCapelli** [comment]
We added a short article to document the feature.

You can find it here:
https://www.basicairdata.eu/projects/android/android-gps-logger/application-note-gpslogger/manual-setup-of-the-egm-altitude-correction-for-basic-air-data-gps-logger/

**Comment by DazzyWalkman** [comment]
Thanks.
