### ISSUE TITLE
App suddenly shift by 2 hours

### ISSUE THREAD

**Issue by jcubic** [BasicAirData/GPSLogger#74]
Not sure what happen maybe app was updated I usually add correction -1 because of daylight saving but now I need to use -2 which is my timezone (+2), so I can assume that it just suddenly ignore my timezone.

**Comment by GrazianoCapelli** [comment]
The app saves all the Timestamps in UTC into its local Datadase and in all supported exportation formats.
KML and GPX standards require to save Timestamps in UTC.

The local Time is used only for Track Names, for user convenience.
To be precise, the Track Name is the local time (based on your Android time zone) of the first point of the track.
The local time differs from UTC time depending on Time Zone and on daylight saving.

As first step, please record a small track, export it in GPX, open it in a text editor and verify that the Trackpoints Timestamps are saved in UTC Time.

The `<time>` field on the Trackpoints should match the UTC one.
`<trkpt lat="45.81270038" lon="13.29805661"><ele>81.000</ele><time>2019-08-12T12:42:58.000Z</time><speed>0.000</speed><sat>14</sat></trkpt>`
To obtain the UTC time you can simply google _UTC Time_.

We await a feedback of your test.

**Comment by jcubic** [comment]
Thanks, that's right gpx have UTC I was using csv file that don't have timezone notation. Maybe it would be good idea to include timezone in csv, as well, but this will be breaking change.
