### ISSUE TITLE
Date time field is wrong

### ISSUE THREAD

**Issue by robbitt** [BasicAirData/GPSLogger#89]
On the app and on exported logs, the date time field is off.  I tested it a few minutes ago (began logging on 2020-08-01 21:28:42) but the logs show 2020-08-02 04:29:03.

I scanned the source code for GPSLogger, and see you've been using loc.getTime() - I am not sure why my android phone is showing the wrong time.

**Comment by GrazianoCapelli** [comment]
The app saves all the Timestamps in UTC into its local Database, and exports it in UTC into all supported exportation formats.
In fact, KML and GPX standards require to save Timestamps in UTC.

The local Time is used only for Track Names, for user convenience.
To be precise, the Track Name is the local time (based on your Android time zone) of the first point of the track.
The local time differs from UTC time depending on Time Zone and on daylight saving.

The Date Time Field you are reporting as wrong is for the Name of the track, for all the recorded points, or for both?

**Comment by robbitt** [comment]
Thank you so very much @GrazianoCapelli - that explains the problem.  I suggest that you make a note about the Timstamp being in UTC format in the docs (i.e. http://www.basicairdata.eu/projects/android/android-gps-logger/ ).  

Great work on this app. I use it quite a bit, and it is perfect at what it does.  I'll write a positive review of what I like about it on Google Play. Cheers!

**Comment by GrazianoCapelli** [comment]
Glad it helped.
We added the topic into the [Frequently Asked Questions](https://github.com/BasicAirData/GPSLogger/blob/master/readme.md#frequently-asked-questions) section.
Thanks for your suggestion!

**Comment by GrazianoCapelli** [comment]
@robbitt - The v2.2.10 added the possibility to view the Time in the local Timezone or in the GPST (UTC time).
Thanks again for your useful Feedback, it helped to make the right decision to include this feature!
